app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    #API data
    path('tests_api/', views.tests_data_api),
    #Create test
    path('create_test/', views.create_test),
    #Create test
    path('update_test/', views.update_test),
    path('delete_test/', views.delete_test)
]

base_setting/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('model_form/', include('model_form.urls')),
    path('html_to_pdf/', include('render_html_to_pdf.urls')),
    path('send_email/', include('send_email.urls')),
    path('donate/', include('donate.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name='core'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.products, name='products'),
    path('customer/<int:pk>/', views.customer, name='customer'),
    path('create-order/<int:pk>', views.create_order, name='create-order'),
    path('update-order/<int:pk>', views.update_order, name='update-order'),
    path('delete-order/<int:pk>', views.delete_order, name='delete-order'),
]

crash_course/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    profile_pic = models.ImageField(null=True, blank=True, default='profile-1.png')
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f'{self.name}'


class Tag(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    CATEGORY = (
            ('Indoor', 'Indoor'),
            ('Out Door', 'Out Door'),
        )
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField(null=True)
    category = models.CharField(max_length=200, choices=CATEGORY, null=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name


class Order(models.Model):
    STATUS = (
            ('Pending','Pending'),
            ('Out for delivery', 'Out for delivery'),
            ('Delivered', 'Delivered')
        )
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)
    note = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.product.name

core/forms.py
from django.forms import ModelForm
from .models import Order


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

core/views.py
from django.shortcuts import render, redirect

from accounts.decorators import allowed_users, admin_only
from .models import *
from .forms import OrderForm
from django.http import HttpResponse
from django.forms import inlineformset_factory
from .filters import OrderFilter
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required(login_url='login')
@admin_only
def home(request):
    orders = Order.objects.all()
    customers = Customer.objects.all()
    total_customers = customers.count()
    total_orders = orders.count()
    delivered = orders.filter(status='Delivered').count()
    pending = orders.filter(status='Pending').count()
    context = {
        'orders': orders,
        'customers' : customers,
        'total_customers': total_customers,
        'total_orders': total_orders,
        'delivered': delivered,
        'pending': pending,
    }
    return render(request, 'core/home.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def products(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(request, 'core/products.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def customer(request, pk):
    customer = Customer.objects.get(id=pk)
    orders = customer.order_set.all()
    order_count = orders.count()
    myFilter = OrderFilter(request.GET, queryset=orders)
    orders = myFilter.qs
    context = {
        'customer': customer,
        'orders': orders,
        'order_count': order_count,
        'myFilter': myFilter,
    }
    return render(request, 'core/customer.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def create_order(request, pk):
    OrderFormSet = inlineformset_factory(Customer, Order, fields=('product', 'status'), extra=10)
    customer = Customer.objects.get(id=pk)
    formset = OrderFormSet(queryset=Order.objects.none(),instance=customer)
    # form = OrderForm(initial={'customer': customer})
    if request.method == 'POST':
        # form = OrderForm(request.POST)
        formset = OrderFormSet(request.POST, instance=customer)
        if formset.is_valid():
            formset.save()
            return redirect('/')
    context = {
        'formset': formset
    }
    return render(request, 'core/order_form.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def update_order(request, pk):
    order = Order.objects.get(id=pk)
    form = OrderForm(instance=order)
    if request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {
        'form': form
    }
    return render(request, 'core/order_form.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def delete_order(request, pk):
    order = Order.objects.get(id=pk)
    if request.method == "POST":
        order.delete()
        return redirect('/')
    context = {
        'item': order
    }
    return render(request, 'core/delete.html', context)

templates/core/customer.html
{% extends 'base.html' %}

{% block title %}Customer{% endblock title %}

{% block content %}

<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Customer:</h5>
            <hr>
            <a class="btn btn-outline-info btn-sm btn-block">Update Customer</a>
            <a class="btn btn-outline-info btn-sm btn-block" href="{% url 'core:create-order' customer.id %}">Place Order</a>
        </div>
    </div>
    <div class="col-md">
        <div class="card card-body">
            <h5>Contact Information</h5>
            <hr>
            <h4>Email: {{ customer.email }}</h4><br>
            <h4>Phone: {{ customer.phone }}</h4>
        </div>
    </div>
    <div class="col-md">
        <div class="card card-body">
            <h5>Total Orders</h5>
            <hr>
            <h1 style="text-align:center; padding:10px;">{{ order_count }}</h1>
        </div>
    </div>
</div>

<br>

<div class="row">
    <div class="col">
        <div class="card card-body">
            <form action="" method="GET">
                {{myFilter.form}}
                <button class="btn btn-primary" type="submit">Search</button>
            </form>
        </div>
    </div>
</div>

<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Product</th>
                    <th>Note</th>
                    <th>Date Ordered</th>
                    <th>Status</th>
                    <th>Update</th>
                    <th>Remove</th>
                </tr>
                {% for order in orders %}
                <tr>
                    <td>{{ order.product }}</td>
                    <td>{{ order.note }}</td>
                    <td>{{ order.date_created }}</td>
                    <td>{{ order.status }}</td>
                    <td><a class="btn btn-sm btn-info" href="{% url 'core:update-order' order.pk %}">Update</a></td>
                    <td><a class="btn btn-sm btn-danger" href="{% url 'core:delete-order' order.pk %}">Delete</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock content %}

templates/core/delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Delete{% endblock %}

{% block content %}
<br>
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">
            <p>Are you want to delete "{{item}}" </p>

            <form action="{% url 'core:delete-order' item.id %}" method="POST">
                {% csrf_token %}
                <input class="btn btn-sm btn-danger" type="submit" name="Delete">
                <a class="btn btn-sm btn-warning" href="{% url 'core:home' %}">Cancel</a>
            </form>

        </div>
    </div>
</div>



{% endblock content %}

templates/core/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

    {% include 'core/status.html' %}

    <br>

    <div class="row">
        <div class="col-md-5">
            <h5>CUSTOMERS:</h5>
            <hr>
            <div class="card card-body">
                <a href="#" class="btn btn-primary btn-sm btn-block">Create Customer</a>
                <table class="table table-sm">
                    <tr>
                        <th></th>
                        <th>Customers</th>
                        <th>Phone</th>
                    </tr>
                    {% for customer in customers %}
                    <tr>
                        <td><a class="btn btn-sm btn-info" href="{% url 'core:customer' customer.id %}">View</a></td>
                        <td>{{ customer.name }}</td>
                        <td>{{ customer.phone }}</td>
                    </tr>
                    {% endfor%}
                </table>
            </div>
        </div>
        <div class="col-md-7">
            <h5>LAST 5 ORDERS</h5>
            <hr>
            <div class="card card-body">
                <table class="table table-sm">
                    <tr>
                        <th>Product</th>
                        <th>Date Ordered</th>
                        <th>Status</th>
                        <th>Update</th>
                        <th>Remove</th>
                    </tr>
                    {% for order in orders %}
                    <tr>
                        <td>{{ order.product }}</td>
                        <td>{{ order.date_created }}</td>
                        <td>{{ order.status }}</td>
                        <td><a class="btn btn-sm btn-info" href="{% url 'core:update-order' order.pk %}">Update</a></td>
                        <td><a class="btn btn-sm btn-danger" href="{% url 'core:delete-order' order.pk %}">Delete</a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

{% endblock content %}

templates/core/nothing.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block content %}
{% endblock content %}

templates/core/order_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Create Order{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">
            <form action="" method="POST">
                {% csrf_token %}
                {{ formset.management_form }}
                {% for form in formset %}
                    {{ form }}
                <hr>
                {% endfor %}
                <input type="submit">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/core/products.html
{% extends 'base.html' %}

{% block title %}Products{% endblock title %}

{% block content %}
    <br>
    <div class="row">
        <div class="col-md">
            <div class="card card-body">
                <h5>Products</h5>
            </div>
            <div class="card card-body">
                <table class="table">
                    <tr>
                        <th>Product</th>
                        <th>Category</th>
                        <th>Price</th>
                    </tr>
                    {% for product in products %}
                    <tr>
                        <td>{{ product.name }}</td>
                        <td>{{ product.category }}</td>
                        <td>{{ product.price }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

{% endblock content %}

templates/core/status.html
<div class="row">
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3" id="total-orders">
                <div class="card-header">
                    <h5 class="card-title">Total Orders</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ total_orders }}</h3>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3" id="orders-delivered">
                <div class="card-header">
                    <h5 class="card-title">Orders Delivered</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ delivered }}</h3>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3" id="orders-pending">
                <div class="card-header">
                    <h5 class="card-title">Orders Pending</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ pending }}</h3>
                </div>
            </div>
        </div>
    </div>
</div>