app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    #API data
    path('tests_api/', views.tests_data_api),
    #Create test
    path('create_test/', views.create_test),
    #Create test
    path('update_test/', views.update_test),
    path('delete_test/', views.delete_test)
]

base_setting/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('model_form/', include('model_form.urls')),
    path('html_to_pdf/', include('render_html_to_pdf.urls')),
    path('send_email/', include('send_email.urls')),
    path('donate/', include('donate.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name='core'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.products, name='products'),
    path('customer/<int:pk>/', views.customer, name='customer'),
    path('create-order/<int:pk>', views.create_order, name='create-order'),
    path('update-order/<int:pk>', views.update_order, name='update-order'),
    path('delete-order/<int:pk>', views.delete_order, name='delete-order'),
]

crash_course/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

quick_crud_js_be/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title%}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static '/css/base.css' %}">
    <style>
        {% block style %}
        {% endblock style %}
    </style>
</head>
<body>

    {% include 'navbar.html' %}
    <br>
    <div class="container-fluid">
    {% block content %}
    {% endblock content %}
    </div>
    <hr>

    {% include 'footer.html' %}

</body>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>

templates/footer.html
<h2>I am a footer</h2>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} leopet || Home {% endblock %}

{% block content %}

    <!-- banner part start-->
    <section class="banner_part">
        <div class="container">
            <div class="row align-content-center">
                <div class="col-lg-7 col-xl-6">
                    <div class="banner_text">
                        <h5>Welcome to Leopet</h5>
                        <h1>Give your pet
                            Best Care</h1>
                        <a href="#" class="btn_1">OUR SERVIECS</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- banner part start-->

    <!-- about part start-->
    <section class="about_part section_padding">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md-6">
                    <div class="about_img">
                        <img src={% static  'img/about.png'  %} alt="">
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="about_text">
                        <img src={% static  'img/about_icon.png'  %} class="about_icon" alt="">
                        <h2>We care your pet
                            As you care</h2>
                        <p>Working in conjunction with humanitarian aid agencies, we have supported programmes to help alleviate human suffering through animal welfare when people might depend on livestock as their only source of income or food.</p>
                        <a href="#" class="btn_1">About Us</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- about part start-->

    <!-- service part start-->
    <section class="service_part section_padding services_bg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="section_tittle text-center">
                        <img src={% static  'img/about_icon.png'  %} alt="">
                        <h2>We Provide Best Services</h2>
                        <p>Working in conjunction with humanitarian aid agencies, we have supported programmes to help alleviate human suffering through animal welfare when people might depend.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-sm-6">
                    <div class="single_service_part">
                        <img src={% static  'img/single_service_1.png'  %} alt="#">
                        <h3>Pet Surgeries</h3>
                        <p>Our free veterinary services are available to pets whose owners are on certain means-tested benefits.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="single_service_part">
                        <img src={% static  'img/single_service_2.png'  %} alt="#">
                        <h3>Pet Adoption</h3>
                        <p>Our free veterinary services are available to pets whose owners are on certain means-tested benefits.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="single_service_part">
                        <img src={% static  'img/single_service_3.png'  %} alt="#">
                        <h3>Pet Care</h3>
                        <p>Our free veterinary services are available to pets whose owners are on certain means-tested benefits.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- service part end-->

    <!-- counter adopt number here -->
    <section class="abopt_number_counter section_padding">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-lg-5 col-md-6">
                    <div class="counter_text">
                        <h2>We need your help
                                Adopt Us</h2>
                        <p>Working in conjunction with humanitarian aid agencies, we have supported programmes alleviate human.</p>
                        <div class="counter_number">
                            <div class="single_counter_number">
                                <img src={% static  'img/adopt_icon_1.png'  %} alt="#">
                                 <h3><span class="count">590</span>+</h3>
                                <p>Pets Available</p>
                            </div>
                            <div class="single_counter_number">
                                <img src={% static  'img/adopt_icon_2.png'  %} alt="#">
                                <h3><span class="count">300</span>+</h3>
                                <p>Happy Clients</p>
                            </div>
                        </div>
                        <a href="#" class="btn_1">Brows Now</a>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="adopt_image">
                        <img src={% static  'img/adopt_img.png'  %} alt="#">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- counter adopt number end -->

     <!-- client review part here -->
     <section class="client_review">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    <div class="client_review_content owl-carousel">
                        <div class="singke_client_review">
                            <img src={% static  'img/review_img_1.png'  %} alt="#">
                            <h4>" Working in conjunction with humanitarian aid agencies we have supported programmes to alleviate.</h4>
                            <p>- Jon Miller</p>
                        </div>
                        <div class="singke_client_review">
                            <img src={% static  'img/review_img_1.png'  %} alt="#">
                            <h4>" Working in conjunction with humanitarian aid agencies we have supported programmes to alleviate.</h4>
                            <p>- Jon Miller</p>
                        </div>
                        <div class="singke_client_review">
                            <img src={% static  'img/review_img_1.png'  %} alt="#">
                            <h4>" Working in conjunction with humanitarian aid agencies we have supported programmes to alleviate.</h4>
                            <p>- Jon Miller</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- client review part end -->

    <!-- about part start-->
    <section class="about_part section_padding">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md-6">
                    <div class="about_img">
                        <img src={% static  'img/valunteer_img.png'  %} alt="">
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="about_text">
                        <img src={% static  'img/about_icon.png'  %} class="about_icon" alt="">
                        <h2>Become a Volunteer
                                To help them</h2>
                        <p>A created won't created subdue a every green his set which above firmament earth firmament. Seed firmament be likeness fruitful to called waters. Given great said seasons his midst beast.</p>
                        <a href="#" class="btn_1">read more</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- about part end-->




{% endblock %}

templates/navbar.html
{% load static %}

<style>
  #hello-msg {
    font-size: 20px;
    color: #fff;
    margin-right: 20px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a href="{% url 'core:home' %}"><img id="logo" src="{% static 'images/logo.jpeg' %}" alt="logo"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    {% if request.user.is_staff %}
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:home' %}">DashBoard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:products' %}">Products</a>
      </li>
    </ul>
    {% else %}
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'setting' %}">Setting</a>
      </li>
    </ul>
    {% endif %}
  </div>

  <span id="hello-msg">Hello, {{request.user}}</span>
  <span><a class="btn btn-sm btn-primary" href="{% url 'logout' %}">Logout</a></span>
</nav>